### ISSUE TITLE
bmcweb::redfish: ThermalSubsystem fan objects should be based on fan inventory FRU and not the sensros

### ISSUE THREAD

**Issue by msbarth** [ibm-openbmc/dev#3513] opened 2022-02-25 19:48 UTC
The Redfish fan objects are incorrectly using the fan inventory endpoints, which reflect the rotors of a fan FRU, instead of the fan FRU level inventory object. This is causing duplicate information to be presented within the ThermalSubsystem and on the GUI for each fan that has more than 1 rotor (i.e. dual rotor fans).

When populating the fan objects within the ThermalSubsystem, the bmcweb code should stop at the fan inventory object path that contains the associations to its related sensors, VPD, etc... and not traverse to the fan inventory object path endpoint.

```
~:$ rfFans
{
  "@odata.id": "/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/",
  "@odata.type": "#FanCollection.FanCollection",
  "Description": "The collection of Fan resource instances chassis",
  "Members": [
    {
      "@odata.id": "/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/fan0_0/"
    },
    {
      "@odata.id": "/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/fan0_1/"
    },
    {
      "@odata.id": "/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/fan1_0/"
    },
    {
      "@odata.id": "/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/fan1_1/"
    },
    {
      "@odata.id": "/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/fan2_0/"
    },
    {
      "@odata.id": "/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/fan2_1/"
    },
    {
      "@odata.id": "/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/fan3_0/"
    },
    {
      "@odata.id": "/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/fan3_1/"
    },
    {
      "@odata.id": "/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/fan4_0/"
    },
    {
      "@odata.id": "/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/fan4_1/"
    },
    {
      "@odata.id": "/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/fan5_0/"
    },
    {
      "@odata.id": "/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/fan5_1/"
    }
  ],
  "Members@odata.count": 12,
  "Name": "Fan Collection"
```
There should only be 6 fans listed above... `fan0 - fan5` and not the represent rotors (i.e. with `_0` or `_1`)

This is causing the GUI to show that there are 12 fans in inventory when really there are only 6:
![Screenshot from 2022-02-25 13-44-00](https://user-images.githubusercontent.com/14202667/155785000-e9f513cf-35f0-4318-b1f8-9417c4b482ed.png)

As shown in the screenshot, this gives the perception of more fans than are actually present in the system and that each one has its own "Identify" LED, which they do not. The fan FRU has the LEDs

*Note: When Redfish should return the fan `sensors`, then the associations should be traversed to the associated fan tach sensors which will have 2 for each fan FRU where the fan is a dual rotor fan (or only 1 sensors for a single rotor fan).

**Comment by zhanghaodi** [comment] 2022-02-26 01:56
@msbarth This was considered at the time. For the speed of the dual-rotor fan, the speeds of the two rotors may be different. If the fan is used as the fanId instead of the fan rotor as the fanId, the fan speed is not easy to select at this time.

**Comment by msbarth** [comment] 2022-02-28 16:31
This bug is not in reference to the fan speeds, which would be on the GUI's sensors page, this is in reference to the inventory and all the information that's currently provided under the `ThermalSubsystem/Fans/*` which is displayed on the GUI's inventory page.

What Redfish path represents the fan's sensor(s) where the rotor speeds would be provided? I do not see those getting provided on the `ThermalSubssytem/Fans/*` paths for each fan.

It appears the bmcweb code has separate methods for what would be represented as a fan inventory object versus a fan sensor object but they appear to be almost identical functionally... why is this? as they represent different information per fan?

**Comment by zhanghaodi** [comment] 2022-03-01 01:10
@msbarth I understand what you mean, in the original version, ThermalSubsystem/Fans/* was also based on inventory instead of sensors,
Later, in the next-level directory, ThermalSubsystem/Fans/fanID, this directory needs to display the attributes of each fan, including the fan speed. At this time, if ThermalSubsystem/Fans/* is based on inventory, then the fan speed displayed by ThermalSubsystem/Fans/fanID, this At that time, because the two rotors have two speeds, it will not be able to express, so finally ThermalSubsystem/Fans/* was changed to be based on sensors.

**Comment by msbarth** [comment] 2022-03-01 19:44
Ok, but can we fix that now so that we add a layer for the fan sensors to the fan FRU level of the ThermalSubsystem?
i.e.)
ThermalSubsystem/Fans/fan0 <== FRU level representing the info from the fan FRU's inventory object on dbus (/xyz/openbmc_project/inventory/system/chassis/motherboard/fan0)

ThermalSubsystem/Fans/fan0/fan0_0 <== Individual fan sensors that would contain that associated sensor's speed

Or is there something prohibiting us from accomplishing this?

We need to fix this representation in Redfish/GUI as there are truly only half the number of represented fans within a system versus the number of fan rotors, which makes a difference in the amount (and what) data is available for the fan FRU versus the fan rotor(s).

**Comment by zhanghaodi** [comment] 2022-03-03 02:57
@msbarth 
https://github.com/ibm-openbmc/bmcweb/pull/271
Modified in this commit, ThermalSubsystem/Fans/fanID does not add the fan speed property,
Do you think this meets the requirements?

**Comment by msbarth** [comment] 2022-03-04 19:33
> @msbarth [ibm-openbmc/bmcweb#271](https://github.com/ibm-openbmc/bmcweb/pull/271) Modified in this commit, ThermalSubsystem/Fans/fanID does not add the fan speed property, Do you think this meets the requirements?

Well, the issue isnt specific to the fan speed property but how the `fanID` objects are constructed. Could you provide the output of the following that shows all the fans with this change:
```
curl -k -H "X-Auth-Token: ${Token}" -X GET https://${BMC}/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans
```

I'm looking for that to return only the number of entries as there are actual fan enclosures(FRUs) and not the number of fan rotors that exist (and of course have the appropriate redfish data associated with the FRU still).

**Comment by zhanghaodi** [comment] 2022-03-07 01:33
Here are the relevant test results:
```
 curl -k -H "X-Auth-Token: $token" -X GET https://${bmc}/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans
{
  "@odata.id": "/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/",
  "@odata.type": "#FanCollection.FanCollection",
  "Description": "The collection of Fan resource instances chassis",
  "Members": [
    {
      "@odata.id": "/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/fan0/"
    },
    {
      "@odata.id": "/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/fan1/"
    },
    {
      "@odata.id": "/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/fan2/"
    },
    {
      "@odata.id": "/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/fan3/"
    }
  ],
  "Members@odata.count": 4,
  "Name": "Fan Collection"
}
 curl -k -H "X-Auth-Token: $token" -X GET https://${bmc}/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/fan1
{
  "@odata.id": "/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/fan1/",
  "@odata.type": "#Fan.v1_0_0.Fan",
  "Id": "fan1",
  "Name": "fan1",
  "Status": {
    "Health": "OK",
    "State": "Absent"
  }
}
```
In the fanID related attributes, the fan speed is not added, which is related to the fan rotor.

**Comment by msbarth** [comment] 2022-03-07 18:37
Ah, ok.. cool. I'll pull down that change and check it out on the same system thru the GUI

**Comment by msbarth** [comment] 2022-03-09 16:25
So with the latest I pulled down from https://github.com/ibm-openbmc/bmcweb/pull/271, now no fans show up in the GUI's inventory which is not what we want and I'm also not able to access the individual fans thru `curl` commands now as well.
```
> curl -k -H "X-Auth-Token: ${rfToken}" -X GET https://${rfBMC}/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans
{
  "@odata.id": "/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/",
  "@odata.type": "#FanCollection.FanCollection",
  "Description": "The collection of Fan resource instances chassis",
  "Members": [
    {
      "@odata.id": "/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/fan0/"
    },
    {
      "@odata.id": "/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/fan1/"
    },
    {
      "@odata.id": "/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/fan2/"
    },
    {
      "@odata.id": "/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/fan3/"
    },
    {
      "@odata.id": "/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/fan4/"
    },
    {
      "@odata.id": "/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/fan5/"
    }
  ],
  "Members@odata.count": 6,
  "Name": "Fan Collection"
}

> curl -k -H "X-Auth-Token: ${rfToken}" -X GET https://${rfBMC}/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/fan0
{
  "error": {
    "@Message.ExtendedInfo": [
      {
        "@odata.type": "#Message.v1_1_1.Message",
        "Message": "The requested resource of type fan named fan0 was not found.",
        "MessageArgs": [
          "fan",
          "fan0"
        ],
        "MessageId": "Base.1.8.1.ResourceNotFound",
        "MessageSeverity": "Critical",
        "Resolution": "Provide a valid resource identifier and resubmit the request."
      }
    ],
    "code": "Base.1.8.1.ResourceNotFound",
    "message": "The requested resource of type fan named fan0 was not found."
  }
}
```
So this change doesnt appear to correctly be handling multi-rotor fans? Did the system you tested on above have dual rotor fans?

**Comment by msbarth** [comment] 2022-03-09 16:29
fyi, I cherry-picked sha `4c1db9707dfe7bdd1a1d2fc1182ff866d048e8c6` in this testing which also looks to have failed CI in the PR.

**Comment by zhanghaodi** [comment] 2022-03-14 03:23
1>Tested machine has dual rotor fans,
```
busctl get-property xyz.openbmc_project.Inventory.Manager /xyz/openbmc_project/inventory/system/chassis/motherboard/fan0 xyz.openbmc_project.Association.Definitions Associations --verbose
ARRAY "(sss)" {
        STRUCT "sss" {
                STRING "sensors";
                STRING "inventory";
                STRING "/xyz/openbmc_project/sensors/fan_tach/fan0_0";
        };
        STRUCT "sss" {
                STRING "sensors";
                STRING "inventory";
                STRING "/xyz/openbmc_project/sensors/fan_tach/fan0_1";
        };
        STRUCT "sss" {
                STRING "leds";
                STRING "inventory";
                STRING "/xyz/openbmc_project/led/physical/front_fan";
        };
        STRUCT "sss" {
                STRING "chassis";
                STRING "inventory";
                STRING "/xyz/openbmc_project/inventory/system/chassis";
        };
        STRUCT "sss" {
                STRING "fault_led_group";
                STRING "fru";
                STRING "/xyz/openbmc_project/led/groups/fan0_fault";
        };
};
```
2>CI bug resolved, updated in https://github.com/ibm-openbmc/bmcweb/pull/271

**Comment by msbarth** [comment] 2022-03-21 17:50
On a dual rotor fan system, I found that the `/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/fan*` now returns the correct representation of the fan FRUs within the system. However, I am now unable to retrieve the individual fan objects from that path to see their associated properties that use to be retrieved from the fan FRU inventory object path:

Redfish retrieve all fan objects from `.../Fans`:
```
> curl -k -H "X-Auth-Token: ${rfToken}" -X GET https://${rfBMC}/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans
{
  "@odata.id": "/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/",
  "@odata.type": "#FanCollection.FanCollection",
  "Description": "The collection of Fan resource instances chassis",
  "Members": [
    {
      "@odata.id": "/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/fan0/"
    },
    {
      "@odata.id": "/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/fan1/"
    },
    {
      "@odata.id": "/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/fan2/"
    },
    {
      "@odata.id": "/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/fan3/"
    },
    {
      "@odata.id": "/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/fan4/"
    },
    {
      "@odata.id": "/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/fan5/"
    }
  ],
  "Members@odata.count": 6,
  "Name": "Fan Collection"
}
```

But try to access on of those individual fan objects:
```
> curl -k -H "X-Auth-Token: ${rfToken}" -X GET https://${rfBMC}/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/fan0
{
  "error": {
    "@Message.ExtendedInfo": [
      {
        "@odata.type": "#Message.v1_1_1.Message",
        "Message": "The requested resource of type fan named fan0 was not found.",
        "MessageArgs": [
          "fan",
          "fan0"
        ],
        "MessageId": "Base.1.8.1.ResourceNotFound",
        "MessageSeverity": "Critical",
        "Resolution": "Provide a valid resource identifier and resubmit the request."
      }
    ],
    "code": "Base.1.8.1.ResourceNotFound",
    "message": "The requested resource of type fan named fan0 was not found."
  }
}
```

Without this update, when retrieving an individual fan object, this is what's returned:
```
> curl -k -H "X-Auth-Token: ${rfToken}" -X GET https://${rfBMC}/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/fan0_0
{
  "@odata.id": "/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/fan0_0/",
  "@odata.type": "#Fan.v1_0_0.Fan",
  "Id": "fan0_0",
  "Location": {
    "PartLocation": {
      "ServiceLabel": "U78DA.ND0.WZS0042-A0"
    }
  },
  "LocationIndicatorActive": false,
  "Manufacturer": "Delta",
  "Model": "7B5G",
  "Name": "fan0_0",
  "PartNumber": "02YK200",
  "SerialNumber": "FA121A06-K28",
  "SparePartNumber": "02YK237",
  "Status": {
    "Health": "OK",
    "State": "Enabled"
  }
}
```

**Comment by zhanghaodi** [comment] 2022-03-22 07:23
The reason for the test failure after the update is:
In https://github.com/ibm-openbmc/openbmc/blob/1020/meta-ibm/recipes-phosphor/inventory/phosphor-inventory-manager/associations.json,
Required for "path": "system/chassis/motherboard/fan0",
  "path": "system/chassis/motherboard/fan1".. this series, need to add a new endpoint,
  ```
             {
                 "types":
                 {
                     "rType": "inventory",
                     "fType": "chassis"
                 },
                 "paths":
                 [
                     "/xyz/openbmc_project/inventory/system/chassis"
                 ]
             },
```
Take "path": "system/chassis/motherboard/fan0" for example
added as:
```
{
        "path": "system/chassis/motherboard/fan0",
        "endpoints":The reason for adding this is that there is an action to verify that the fanid is valid in the code to ensure that the fanid is associated with the corresponding chassis
        [
            {
                "types":
                {
                    "rType": "inventory",
                    "fType": "sensors"
                },
                "paths":
                [
                    "/xyz/openbmc_project/sensors/fan_tach/fan0_0",
                    "/xyz/openbmc_project/sensors/fan_tach/fan0_1"
                ]
            },
            {
                "types":
                {
                    "rType": "inventory",
                    "fType": "leds"
                },
                "paths":
                [
                    "/xyz/openbmc_project/led/physical/fan0"
                ]
            }
            {
                "types":
                {
                    "rType": "inventory",
                    "fType": "chassis"
                },
                "paths":
                [
                    "/xyz/openbmc_project/inventory/system/chassis"
                ]
            },
        ]
    },
```
The reason for adding this is that there is an action to verify that the fanid is valid in the code to ensure that the fanid is associated with the corresponding chassis.

This is why our test results are different.
After you add this endpoint, test it, curl -k -H "X-Auth-Token: ${rfToken}" -X GET https://${rfBMC}/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/ fan0
Whether it can return successfully.

**Comment by msbarth** [comment] 2022-03-22 20:46
Ah, thanks for the info on what's needed in the `associations.json`! I was able to update this and check this out with a dual rotor fan system and from what I can tell its working as expected with your fix. I need to check a few more things thru Redfish and would like to spot check on a single rotor setup, but it appears to be working good so far, thanks!

**Comment by msbarth** [comment] 2022-03-23 15:05
My verification of this change looks good! Thanks for the help getting this fixed up.

**Comment by msbarth** [comment] 2022-03-23 15:06
Will need to coordinate getting the `associations.json` files updated along with this change to bmcweb.

**Comment by spinler** [comment] 2022-04-01 13:47
Hi @zhanghaodi, we noticed on a system with an external IO drawer, meaning multiple chassis, that getting the Fans for 1 chassis gets all of  them:

```
curl -k -X GET .../redfish/v1/Chassis/chassis/ThermalSubsystem/Fans
{
  "@odata.id": "/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/",
  "@odata.type": "#FanCollection.FanCollection",
  "Description": "The collection of Fan resource instances chassis",
  "Members": [
    {
      "@odata.id": "/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/fan0/"
    },
    {
      "@odata.id": "/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/fan1/"
    },
    {
      "@odata.id": "/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/fan2/"
    },
    {
      "@odata.id": "/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/fan3/"
    },
    {
      "@odata.id": "/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/fan4/"
    },
    {
      "@odata.id": "/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/fan5/"
    },
    {
      "@odata.id": "/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/fan1/"
    },
    {
      "@odata.id": "/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/fan2/"
    },
    {
      "@odata.id": "/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/fan3/"
    },
    {
      "@odata.id": "/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/fan4/"
    },
    {
      "@odata.id": "/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/fan1/"
    },
    {
      "@odata.id": "/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/fan2/"
    },
    {
      "@odata.id": "/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/fan3/"
    },
    {
      "@odata.id": "/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/fan4/"
    }
  ],
```

Looks like getValidFan() doesn't compare the chassis ID when building its response?

**Comment by zhanghaodi** [comment] 2022-04-02 01:28
@spinler

**Comment by zhanghaodi** [comment] 2022-04-02 01:30
Hi,@spinler 
There is a getValidChassis method. The get method compares whether the ChassisId is equal. See the test result about a system with an external IO drawer.
/redfish/v1/Chassis/ChassisId/ThermalSubsystem/Fans/fanId/
The chassisId of the other two chassis is also chassis, which is the cause of this problem. It is recommended to name the chassisId of the other two chassis to a different ID from chassis.

**Comment by spinler** [comment] 2022-04-02 16:15
But getValidFan() ignores the chassis ID passed in when determining which fans to use...
It uses a GetSubTree to find all fans, and then assigns them all the chassis ID passed in even though some of those fans are from another chassis.  That also aligns with the results I posted above showing the fans from the MEX also showing up under the main chassis.

**Comment by mikecgithub** [comment] 2022-04-04 20:30
I am working on a fix for this that doesn't add a fan unless the inventory path includes the proper chassis string. will update the ticket once I begin testing.

**Comment by zhanghaodi** [comment] 2022-04-07 03:03
Hi, @spinler 
https://github.com/ibm-openbmc/bmcweb/pull/317
Added the verification of chassisID in the above submission, could you help to test whether this meets the requirements?

**Closed as completed** 2022-08-03 18:19 UTC
Labels: bug, ReadyForDev
