### ISSUE TITLE
eBMC GUI : remove Redfish hardcoded hypermedia paths

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#3299] opened 2021-08-10 20:40 UTC
## Tasks (Delete when completed)
- [ ] Add the milestone
- [ ] Add to the Epic pipeline
- [ ] Create as Epic
- [ ] Add UI story or stories to support the Epic using the UI Story template

## Summary
- [ ] Add brief summary of the overall Epic
    - Is this part of a new or existing Information Architecture
    - Is this just a wrapper for the stories created for each design / fed stages

## References/Resources
- [ ] Add eBMC Feature Item <add item number>
- [ ] Add feature discovery folder (create if doesn't exist)

**Comment by rfrandse** [comment] 2021-08-11 11:07
refresh

**Comment by rfrandse** [comment] 2021-08-19 11:07
refresh

**Comment by rfrandse** [comment] 2021-08-24 11:06
refresh

**Comment by rfrandse** [comment] 2021-08-28 11:10
refresh

**Comment by dixsie** [comment] 2021-09-17 17:34
duplicate of  #2740

**Closed by dixsie** 2021-09-17 17:34 UTC
Labels: Epic, GUI
