### ISSUE TITLE
Power / Cooling - EPOW

### ISSUE THREAD

**Issue by rfrandse** [ibm-openbmc/dev#140] opened 2018-08-21 16:32 UTC
<a href="https://github.com/anoo1"><img src="https://avatars0.githubusercontent.com/u/9052527?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [anoo1](https://github.com/anoo1)**
_Tuesday Jun 14, 2016 at 19:44 GMT_
_Originally opened as https://github.com/openbmc/openbmc/issues/346_

----

Placeholder for EPOW support functions on future systems.

**Comment by rfrandse** [comment] 2018-08-21 16:32
<a href="https://github.com/geissonator"><img src="https://avatars2.githubusercontent.com/u/1612261?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [geissonator](https://github.com/geissonator)**
_Tuesday Jan 16, 2018 at 19:52 GMT_

----

A lot of this is sending events up to the OS to let them know when bad things are starting to happen (fans starting to fail, ambient rising, ...) to allow a controlled shutdown.

**Comment by rfrandse** [comment] 2019-02-18 02:13
refresh

**Comment by rfrandse** [comment] 2019-02-25 02:13
refresh

**Comment by rfrandse** [comment] 2019-03-03 14:14
refresh

**Comment by rfrandse** [comment] 2019-03-10 13:14
refresh

**Comment by rfrandse** [comment] 2019-03-17 13:14
refresh

**Comment by rfrandse** [comment] 2019-03-24 13:14
refresh

**Comment by rfrandse** [comment] 2019-03-31 13:15
refresh

**Comment by rfrandse** [comment] 2019-04-07 13:15
refresh

**Comment by rfrandse** [comment] 2019-04-14 13:15
refresh

**Comment by rfrandse** [comment] 2019-04-21 13:16
refresh

**Comment by rfrandse** [comment] 2019-04-28 13:17
refresh

**Comment by rfrandse** [comment] 2019-05-12 13:21
refresh

**Comment by rfrandse** [comment] 2019-05-19 13:21
refresh

**Comment by rfrandse** [comment] 2019-05-26 13:28
refresh

**Comment by rfrandse** [comment] 2019-06-02 13:33
refresh

**Comment by rfrandse** [comment] 2019-06-09 13:34
refresh

**Comment by rfrandse** [comment] 2019-06-23 13:38
refresh

**Comment by derekhoward55** [comment] 2019-07-10 16:03
Closing this as dupe of issue 585

**Closed by derekhoward55** 2019-07-10 16:03 UTC
Labels: Epic, prio_low
