### ISSUE TITLE
GUI : FED : LDAP error moving from AD to openldap

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#1186] opened 2019-09-17 20:17 UTC
SW471632. 
Need to Disable the active configuration (e.g. AD)
Then enable the desired configuration (e.g. openldap)

**Comment by gtmills** [comment] 2019-09-17 20:19
If moving from openldap to AD would need to do the same.
// Disable the openLDAP service
curl -k -H "X-Auth-Token: $bmc_token" -X PATCH https://${BMC_IP}/redfish/v1/AccountService/ -D patch.txt -d '{"LDAP":{"ServiceEnabled":false}}'


// Enable the AD service
curl -k -H "X-Auth-Token: $bmc_token" -X PATCH https://${BMC_IP}/redfish/v1/AccountService/ -D patch.txt -d '{"ActiveDirectory":{"ServiceEnabled":true}}'.

**Comment by derick-montague** [comment] 2019-09-17 21:41
The current implementation sends both AD and LDAP properties. This works when going from AD to OpenLDAP, but not in the reverse. The suggested solution will be to make multiple requests from the GUI. The fist will be to disable AD and once it's returned, the second request to enable LDAP. 

This was the agreed upon pattern in the community based on conversation with @ratagupt.

**Comment by derick-montague** [comment] 2019-09-19 23:23
Verified that the issue is that in order to change from AD to LDAP, AD has to be disabled first and after it is disabled, LDAP can be enabled.

**Comment by derick-montague** [comment] 2019-10-01 15:25
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/25508

**Comment by rfrandse** [comment] 2019-10-10 13:01
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/25508 merged

**Closed by rfrandse** 2019-10-10 13:01 UTC
Labels: GUI, UI FED, bug
