### ISSUE TITLE
rainier: ethernet link failover service is failing

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#1237] opened 2019-10-01 19:04 UTC
Need to discuss whether we even want this on future products.

```
root@rainier:/lib/systemd/system# journalctl | grep ncsi
Jan 01 00:00:17 rainier ncsi-netlink[269]: Failed to resolve
Jan 01 00:00:17 rainier systemd[1]: ncsi-netlink.service: Main process exited, code=exited, status=244/n/a
Jan 01 00:00:17 rainier systemd[1]: ncsi-netlink.service: Failed with result 'exit-code'.
```

**Comment by mzipse** [comment] 2021-02-15 20:10
@ratagupt this was a carryover from our OP940 functionality to make sure it got carried forward to eBMC.  Is this still needed for eBMC?  Is there work that we need to plan for for this?  Are you the right person I should be asking for this?

**Comment by ratagupt** [comment] 2021-04-05 11:43
@mzipse Let @gkeishin to confirm the same.

**Comment by gkeishin** [comment] 2021-04-06 13:35
This problem still exist and seen time to time on the system and catches in Jenkins HW CI test runs. @mzipse @ratagupt

**Comment by mzipse** [comment] 2021-04-27 14:28
@shenki is this the same as #1243 ?

**Comment by ratagupt** [comment] 2021-05-07 05:55
Seems need to work on this as confirmed by the @shenki

**Comment by sunharis** [comment] 2021-08-03 13:39
Update from George: There is no functional issues due to this ncsi-netlink errors. Moving to GA2

**Comment by sunharis** [comment] 2022-11-03 08:05
We need to evaluate if this is still an issue on the latest drivers of FW1030

**Comment by sunharis** [comment] 2022-11-03 08:05
Migrate-Yes

**Comment by rfrandse** [comment] 2022-12-14 17:12
tracking in jira

**Closed by rfrandse** 2022-12-14 17:12 UTC
Labels: Milestone Tgt
