### ISSUE TITLE
GUI : FED : Move Event log API to Redfish 

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#2070] opened 2020-04-13 16:32 UTC
For event logs, can use 
` https://${bmc}/redfish/v1/Systems/system/LogServices/EventLog/Entries`

instead of ` .get('/xyz/openbmc_project/logging/enumerate')`

https://github.com/openbmc/webui-vue/blob/97f4187e1bac021ea7b5a0f5a780a3d4004edf64/src/store/modules/Health/EventLogStore.js#L67

**Comment by gtmills** [comment] 2020-04-13 17:09
This is blocked by not having the resolved property.. :(

**Comment by derick-montague** [comment] 2020-05-05 16:34
I think we can close this as a duplicate of #1211

**Comment by yoshiemuranaka** [comment] 2020-05-05 16:43
I wouldn't mind keeping it to help break down the event log page story

**Comment by derick-montague** [comment] 2020-05-05 17:57
Great! I added a dependency and reassigned to you. Thanks, Yoshie!

**Comment by yoshiemuranaka** [comment] 2020-05-08 15:51
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/32082

**Closed** 2020-05-21 12:39 UTC
Labels: GUI, Milestone Tgt, UI FED
