### ISSUE TITLE
Redfish: Fix System IndicatorLED

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#1202] opened 2019-09-20 18:52 UTC
``` 
1. bash-4.1$ curl -k -H "X-Auth-Token: $bmc_token" d "{\"data\": false}" -X PUT https://$BMC_IP/xyz/openbmc_project/led/groups/enclosure_identify/attr/Asserted
{
  "data": null,
  "message": "200 OK",
  "status": "ok"


2. Run below command to verify the status of identifier LED via redfish.

bash-4.1$ curl -k -H "X-Auth-Token: $bmc_token" X GET https://${BMC_IP}/redfish/v1/Systems/system                                                  {
  "@odata.context": "/redfish/v1/$metadata#ComputerSystem.ComputerSystem",
  "@odata.id": "/redfish/v1/Systems/system",
  "@odata.type": "#ComputerSystem.v1_6_0.ComputerSystem",
  "Actions": {
    "#ComputerSystem.Reset": {
      "ResetType@Redfish.AllowableValues": [
        "On",
        "ForceOff",
        "ForceOn",
        "ForceRestart",
        "GracefulRestart",
        "GracefulShutdown",
        "PowerCycle",
        "Nmi"
      ],
      "target": "/redfish/v1/Systems/system/Actions/ComputerSystem.Reset"
    }
  },
  "AssetTag": "",
  "BiosVersion": "IBM-witherspoon-OP9-v2.4-9.24",
  "Boot": {
    "BootSourceOverrideEnabled": "Disabled",
    "BootSourceOverrideMode": "Legacy",
    "BootSourceOverrideTarget": "None",
    "BootSourceOverrideTarget@Redfish.AllowableValues": [
      "None",
      "Pxe",
      "Hdd",
      "Cd",
      "Diags",
      "BiosSetup"
    ]
  },
  "Description": "Computer System",
  "Id": "131883A.........",
  "IndicatorLED": "Off",                                      -----> Status is off
  "Links": {
    "Chassis": [
      {
        "@odata.id": "/redfish/v1/Chassis/chassis"
      }
    ],
    "ManagedBy": [
      {
        "@odata.id": "/redfish/v1/Managers/bmc"
      }
    ]
  },
  "LogServices": {
    "@odata.id": "/redfish/v1/Systems/system/LogServices"
  },
  "Manufacturer": "",
  "Memory": {
    "@odata.id": "/redfish/v1/Systems/system/Memory"
  },
  "MemorySummary": {
    "Status": {
      "State": "Enabled"
    },
    "TotalSystemMemoryGiB": 0
  },
  "Model": "8335-GTC........",
  "Name": "system",
  "PartNumber": "",
  "PowerState": "Off",
  "ProcessorSummary": {
    "Count": 2,
    "Status": {
      "State": "Enabled"
    }
  },
  "Processors": {
    "@odata.id": "/redfish/v1/Systems/system/Processors"
  },
  "SerialNumber": "131883A.........",
  "Status": {
    "Health": "OK",
    "HealthRollup": "OK",
    "State": "Disabled"
  },
  "SystemType": "Physical"
}

3. Run below command to assert.

bash-4.1$ curl -k -H "X-Auth-Token: $bmc_token" -d "{\"data\": true}" -X PUT https://$BMC_IP/xyz/openbmc_project/led/groups/enclosure_identify/attr/Asserted
{
  "data": null,
  "message": "200 OK",
  "status": "ok"

4. Run below command to verify the LED status.

bash-4.1$ curl -k -H "X-Auth-Token: $bmc_token" X GET https://${BMC_IP}/redfish/v1/Systems/system                                                  {
  "@odata.context": "/redfish/v1/$metadata#ComputerSystem.ComputerSystem",
  "@odata.id": "/redfish/v1/Systems/system",
  "@odata.type": "#ComputerSystem.v1_6_0.ComputerSystem",
  "Actions": {
    "#ComputerSystem.Reset": {
      "ResetType@Redfish.AllowableValues": [
        "On",
        "ForceOff",
        "ForceOn",
        "ForceRestart",
        "GracefulRestart",
        "GracefulShutdown",
        "PowerCycle",
        "Nmi"
      ],
      "target": "/redfish/v1/Systems/system/Actions/ComputerSystem.Reset"
    }
  },
  "AssetTag": "",
  "BiosVersion": "IBM-witherspoon-OP9-v2.4-9.24",
  "Boot": {
    "BootSourceOverrideEnabled": "Disabled",
    "BootSourceOverrideMode": "Legacy",
    "BootSourceOverrideTarget": "None",
    "BootSourceOverrideTarget@Redfish.AllowableValues": [
      "None",
      "Pxe",
      "Hdd",
      "Cd",
      "Diags",
      "BiosSetup"
    ]
  },
  "Description": "Computer System",
  "Id": "131883A.........",
  "Links": {                                               ----------> Entry for the LED is missing.
    "Chassis": [
      {
        "@odata.id": "/redfish/v1/Chassis/chassis"
      }
    ],
    "ManagedBy": [
      {
        "@odata.id": "/redfish/v1/Managers/bmc"
      }
    ]
  },
  "LogServices": {
    "@odata.id": "/redfish/v1/Systems/system/LogServices"
  },
  "Manufacturer": "",
  "Memory": {
    "@odata.id": "/redfish/v1/Systems/system/Memory"
  },
  "MemorySummary": {
    "Status": {
      "State": "Enabled"
    },
    "TotalSystemMemoryGiB": 0
  },
  "Model": "8335-GTC........",
  "Name": "system",
  "PartNumber": "",
  "PowerState": "Off",
  "ProcessorSummary": {
    "Count": 2,
    "Status": {
      "State": "Enabled"
    }
  },
  "Processors": {
    "@odata.id": "/redfish/v1/Systems/system/Processors"
  },
  "SerialNumber": "131883A.........",
  "Status": {
    "Health": "OK",
    "HealthRollup": "OK",
    "State": "Disabled"
  },
  "SystemType": "Physical",
  "error": {
    "@Message.ExtendedInfo": [
      {
        "@odata.type": "/redfish/v1/$metadata#Message.v1_0_0.Message",
        "Message": "The request failed due to an internal service error.  The service is still operational.",
        "MessageArgs": [],
        "MessageId": "Base.1.4.0.InternalError",
        "Resolution": "Resubmit the request.  If the problem persists, consider resetting the service.",
        "Severity": "Critical"
      }
    ],
    "code": "Base.1.4.0.InternalError",
    "message": "The request failed due to an internal service error.  The service is still operational."
  }
```

**Comment by gtmills** [comment] 2019-09-20 18:54
We don't have a xyz.openbmc_project.LED.Controller.identify so this call fails on our systems:
https://github.com/openbmc/bmcweb/blob/944ffaf9ccae2a084cd650370facfb3f76701186/redfish-core/lib/systems.hpp#L650

**Comment by geissonator** [comment] 2019-09-26 15:22
@vishwabmc any reason we don't have this in our LED groups?

**Comment by gtmills** [comment] 2019-09-26 15:47
Conversation around this on IRC
```GunnarM> jfei, We don't have a xyz.openbmc_project.LED.Controller.identify so this call fails on our systems:
<GunnarM> https://github.com/openbmc/bmcweb/blob/944ffaf9ccae2a084cd650370facfb3f76701186/redfish-core/lib/systems.hpp#L650
<GunnarM> Can you help me understand your LED setup a little more? e.g. xyz.openbmc_project.LED.Controller.identify 
<jfei> Not sure the question? It's just the chassis ID led. Same thing as the ipmitool chassis identify command
<jfei> looks like they should have used enclosure_identify instead of calling the led directly https://github.com/openbmc/phosphor-dbus-interfaces/blob/master/xyz/openbmc_project/Led/README.md
<jfei> Under Mandatory groups
* vijay has quit (Read error: Connection reset by peer)
<GunnarM> Or a GetSubTree(xyz.openbmc_Project.Led.Group) call to the Mapper, find the "enclosure_identify", then a GetAll call to that service. 
<jfei> sure, if there are other led implementations that would cover it as well, although I think we all use the LED GroupManager at this point```

**Comment by vishwabmc** [comment] 2019-10-10 12:02
I think we have discussed in the internal channel. The problem is that, we don't have "Identify" as the physical LED name. Also, from an external user, the target must be "LedGroup" as opposed to "Physical Led".. So in this case: we should have received enclosure_identify.

For example: 

  "data": {
    "Asserted": false
  },

This says that the ID leds are `off`. 

When it is set to `true`, it just says that the physical LEDs are in some state. they can be Blink / ON as defined by the system engineer.

I am not sure what does Redfish expect. I think we need to discuss this bit more..

May be: we need a way to get the mapping physical LED and the desired action. It can be obtained from the led map.

**Comment by wangkair** [comment] 2019-10-31 02:15
Closed by https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/26440

**Closed by wangkair** 2019-10-31 02:15 UTC
Labels: ReadyForDev, bug, help wanted
