### ISSUE TITLE
wspoon ncsi: Top port unplugged/link down causes loss of network connectivity on bottom port

### ISSUE THREAD

**Issue by msbarth** [ibm-openbmc/dev#745] opened 2019-05-22 16:11 UTC
I've found whenever the top BMC network port is unplugged(or link down) the bottom network port loses connectivity as well. I've checked, and back on a previous release (-r32), this was not the case. This only seems to be the case with recent builds and I've got the OS updated with Ubuntu 18.04 and Broadcom fw is at v1.4.80.

The only thing I've noticed that looks odd was in the serial console when all network connectivity to the BMC is lost:
```
[  115.964324] ftgmac100 1e660000.ethernet eth0: Set package 0x0, channel 0x0 as preferred
[  115.986534] ftgmac100 1e660000.ethernet eth0: NCSI: No channel with link found, configuring channel 0
```

## Expected Behavior
BMC network connectivity not impacted when top port is unplugged

## Actual Behavior
All BMC network connectivity is lost

## Steps to Reproduce the Problem

  1. Use OP940 -r1 (or upstream master) on wspoon
  2. Connect both top and bottom BMC network ports
  3. Disconnect top network port and attempt to access BMC thru bottom network connection

**Comment by sammj** [comment] 2019-05-22 21:29
> Expected Behavior
BMC network connectivity not impacted when top port is unplugged

You may want to revise your expecations :) In https://github.com/openbmc/openbmc/issues/2931 OpenBMC requested that failover to the second port be disabled for Witherspoon. I implemented this by making it configurable via a netlink service that a service file in the Witherspoon image configures. Failover works as normal on any other platform since they don't include the service file.

**Comment by jk-ozlabs** [comment] 2019-05-23 03:15
Sounds like it's working as designed - closing. Let me know if we need to revise anything.

**Closed by jk-ozlabs** 2019-05-23 03:15 UTC
Labels: bug

**Comment by msbarth** [comment] 2019-05-23 14:20
Ha, I was not aware of this being a requested feature :)
I've given a reference to this issue, jic, so it's known when the release notes/fix list is wrote up for atleast OP940 since that's where I initially found it.
