### ISSUE TITLE
eBMC State Management - Timed Power On

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#869] opened 2019-05-30 13:44 UTC
Need PLDM message defined for host to call and code on OpenBMC side to support it..

**Comment by rfrandse** [comment] 2019-06-02 13:00
refresh

**Comment by rfrandse** [comment] 2019-06-09 13:01
refresh

**Comment by rfrandse** [comment] 2019-06-16 13:05
refresh

**Comment by rfrandse** [comment] 2019-06-23 13:06
refresh

**Comment by vishwabmc** [comment] 2019-06-26 08:07
Went through the existing implementation and had the discussion with the Paul on the PHYP time management algorithm. We don't have the legacy RTIM implementation for time keeping now so need to get onto the new xyz/openbmc_project/Time.

My current approach to this is ( good path ):

--> OS will push the TPO value to PHYP ( Time since epoch )
   --> PHYP will use a PLDM command to push it onto the BMC
       ( Need to identify what command can this be )
         --> BMC PLDM layer will catch and call the handlers
             --> Handler will invoke an API to a new stand-alone application that handles TPO request

--> The new standalone daemon:
         --> Will save the TPO time
            --> check what is the HOST TIME from the Dbus
              --> Run the timer if needed
                --> Fire the Power On on timer expiration if the conditions are met
                     --> Timer expires
                         --> Fires a Power On.

**Comment by vishwabmc** [comment] 2019-07-12 09:17
In discussion with PLDM folks, sending the "seconds since epoch" from PHYP is still possible and would be part of a PLDM numeric effector.. But such a code does not exist today and we need to implement.

@mine260309 is this something that your team would be interested in ?

**Comment by mine260309** [comment] 2019-07-15 02:54
@vishwabmc Yes. However, it requires the hardware which is not available yet, so we could not really work on this task for now.

**Comment by vishwabmc** [comment] 2019-07-29 07:37
Some reference materials for PLDM / MCTP: 

https://github.com/openbmc/libmctp
https://github.com/openbmc/pldm

**Comment by vishwabmc** [comment] 2019-08-05 09:50
Could break each one of these into multiple stories:

[-] Implement a PLDM command/response that would handle an intege  indicating a desire to do TPO or not. A Policy basically.

[-] Implement a PLDM command/response that would carry an integer value indicating the TPO value ( seconds since epoch )

[-] PLDM handler to invoke the TPO standalone daemon supplying the above data

[-] Implementation of TPO daemon that will:
    - handle above data
    - Trigger State Manager function as part of TPO timer expiration.

**Comment by mine260309** [comment] 2019-12-02 07:27
Based on @vishwabmc 's detailed description, the tasks are divided into two parts:
* In PLDM:
   * Design and add new OEM command(s) for TPO
   * Implement encoder/decoder of the OEM command(s) in libpldm
   * Implement the responder in libpldmresponder
* The TPO deamon
   * Design and add the D-Bus interface, including the TPO value, and the setting (need further discussion)
   * Implement the D-Bus interface in a the new TPO damon.

Several questions to @vishwabmc:
1. Should the TPO feature has a global setting to enable/disable?
   E.g. when it is disabled, the daemon will report error on setting TPO timer, and getting the TPO timer will return 0;
2. If the above answer is yet, will the host be able to set the above setting?
   E.g. host could first enable the TPO, and then set the TPO timer, both via PLDM.
3. When the TPO is enabled and the timer is set, and when the time is going to fire, what should BMC do if BMC is not ready to boot host?
   E.g. when TPO is going to boot host on 9:00 am, and BMC is rebooted during this period, should BMC boot host after it goes to ready state (e.g. at 9:02 am)?

**Comment by vishwabmc** [comment] 2019-12-03 09:45
> Several questions to @vishwabmc:
> 
>     1. Should the TPO feature has a setting to enable/disable (e.g. in `/xyz/openbmc_project/settings`)?
>        E.g. when it is disabled, the daemon will report error on setting TPO timer, and getting the TPO timer will return 0;
> 

- Since this being a feature used by host, it may not be a user settable entity. Is there a way we can gate the external writes to this _and_ allow internal writes only ?



>     2. If the above answer is yes, will the host be able to set the above setting?
>        E.g. host could first enable the TPO and then set the TPO timer, both via PLDM.
>

 - Irrespective of a setting in /xyz, `host` should be able to send a command to enable / disable. So this is anyway needed

 
>     3. When the TPO is enabled and the timer is set, and when the time is going to fire, what should BMC do if BMC is not ready to boot host?

>        E.g. when TPO is going to boot host at 9:00 am, and BMC is rebooted during this period, should BMC boot host after it goes to ready state (e.g. at 9:02 am)?

 - Correct. BMC needs to check if there was a TPO that had to serviced and do so.

**Comment by vishwabmc** [comment] 2019-12-03 09:47
The first thing is to have the PLDM back-end ready to carry the policy and the time since epoch
We would also need to have a PLDM response indicating the SUCCESS or FAILURE ( with corresponding integer return codes )

**Comment by mine260309** [comment] 2019-12-04 09:39
> Since this being a feature used by host, it may not be a user settable entity. Is there a way we can gate the external writes to this and allow internal writes only ?

What do you mean by "internal writes"? Do you mean this setting is not settable by BMC's sysadmin , but only by Host firmware?

> Irrespective of a setting in /xyz, host should be able to send a command to enable / disable. So this is anyway needed

The reason why I ask if there should be such a setting is because host is able to set the TPO without enable/disable setting. E.g.
* Host sets TPO to 0 indicates that TPO is disabled;
* Host set TOP to a valid date indicates that TPO is enabled and the timer is set

Do we really need a separated setting for the feature's enable/disable state? Especially you mentioned that the setting is only set internally (which I interpret as Host firmware could enable/disable it)

> Correct. BMC needs to check if there was a TPO that had to be serviced and do so.

OK, sounds reasonable.

**Comment by vishwabmc** [comment] 2019-12-06 11:56
> > Since this being a feature used by host, it may not be a user settable entity. Is there a way we can gate the external writes to this and allow internal writes only ?
> 
> What do you mean by "internal writes"? Do you mean this setting is not settable by BMC's sysadmin , but only by Host firmware?
> 

Correct. This is an InBand mechanism only. So nothing needed in `/xyz/openbmc`

> > Irrespective of a setting in /xyz, host should be able to send a command to enable / disable. So this is anyway needed
> 
> The reason why I ask if there should be such a setting is because host is able to set the TPO without enable/disable setting. E.g.
> 
>     * Host sets TPO to 0 indicates that TPO is disabled;
> 
>     * Host set TOP to a valid date indicates that TPO is enabled and the timer is set
>

I agree with this. A value of [0] indicates no TPO.
 
> 
> Do we really need a separated setting for the feature's enable/disable state? Especially you mentioned that the setting is only set internally (which I interpret as Host firmware could enable/disable it)
> 
> > Correct. BMC needs to check if there was a TPO that had to be serviced and do so.
> 
> OK, sounds reasonable.

**Comment by mine260309** [comment] 2019-12-09 05:59
Good, so a summary:

* The TPO deamon
   * There is no need for a setting to enable/disable TPO;
      * Setting 0 to disable TPO;
      * Setting a valid date to enable TPO;
   * An interface will be added to phosphor-dbus-interface, and we will ask the community to see if it shall be put in `/xyz/openbmc_project/` or `/org/open_power/`
   * A new TPO service will be created to implement the above interface;
* PLDM
   * Add PDR config for TPO
   * Implement SetNumericEffecter (or equivalent) command

**Comment by vishwabmc** [comment] 2019-12-09 10:41
@mine260309 just want to add that "PowerOn must only be attempted if the system is in Normal Mode". Normal / Manual is a policy settable by user. But I believe, we could bake checking that into some systemd target and not needed part of any code

**Comment by mine260309** [comment] 2019-12-10 03:26
@vishwabmc Could you elaborate on what the "Normal/Manual" mode is? Is it a property on D-Bus, or something else?

**Comment by vishwabmc** [comment] 2019-12-10 10:21
@mine260309 This would be a setting in `/xyz/openbmc`, But we still need to see what is the best way to implement such a setting. For now, please ignore that setting. When we device such a setting, it would be a matter of checking that in some systemd target.. so no code changes would be needed.

**Comment by rfrandse** [comment] 2019-12-10 11:40
refresh

**Comment by wangkair** [comment] 2019-12-16 08:59
Where can we implement the interface? In phospher-state-manager or in a new built project?
@vishwabmc @geissonator

**Comment by vishwabmc** [comment] 2019-12-16 09:10
> Where can we implement the interface? In phospher-state-manager or in a new built project?
> @vishwabmc @geissonator

@wangkair it will `not` be as part of phosphor-state-manager. it would be a different one.

To start with, could you help with PLDM changes ?

**Comment by wangkair** [comment] 2019-12-16 09:42
> > Where can we implement the interface? In phospher-state-manager or in a new built project?
> > @vishwabmc @geissonator
> 
> @wangkair it will `not` be as part of phosphor-state-manager. it would be a different one.
> 
> To start with, could you help with PLDM changes ?

Oh, I assigned the sub-issue to implement the interface, since I have no experience on interface coding and I want to learn it. :-)

**Comment by vishwabmc** [comment] 2019-12-16 11:24
> 
> Oh, I assigned the sub-issue to implement the interface, since I have no experience on interface coding and I want to learn it. :-)

Sure..  We can implement this as a separate daemon inside phosphor-state-manager repo.  Not sure if this is what you asked me before.

**Comment by rfrandse** [comment] 2020-01-03 11:39
refresh

**Comment by rfrandse** [comment] 2020-01-06 11:40
refresh

**Comment by rfrandse** [comment] 2020-01-07 11:40
refresh

**Comment by rfrandse** [comment] 2020-01-09 11:42
refresh

**Comment by rfrandse** [comment] 2020-01-10 11:40
refresh

**Comment by rfrandse** [comment] 2020-01-15 11:45
refresh

**Comment by rfrandse** [comment] 2020-02-04 11:41
refresh

**Comment by rfrandse** [comment] 2020-02-05 11:40
refresh

**Comment by rfrandse** [comment] 2020-02-26 23:22
refresh

**Comment by rfrandse** [comment] 2020-02-27 11:45
refresh

**Comment by rfrandse** [comment] 2020-03-03 11:49
refresh

**Comment by rfrandse** [comment] 2020-03-04 11:28
refresh

**Comment by rfrandse** [comment] 2020-03-10 10:28
refresh

**Comment by rfrandse** [comment] 2020-03-11 10:28
refresh

**Comment by rfrandse** [comment] 2020-03-12 10:27
refresh

**Comment by rfrandse** [comment] 2020-03-13 10:29
refresh

**Comment by rfrandse** [comment] 2020-03-14 10:27
refresh

**Comment by rfrandse** [comment] 2020-03-16 10:28
refresh

**Comment by rfrandse** [comment] 2020-03-19 10:51
refresh

**Comment by rfrandse** [comment] 2020-03-20 10:49
refresh

**Comment by rfrandse** [comment] 2020-03-24 15:59
refresh

**Comment by rfrandse** [comment] 2020-03-27 10:50
refresh

**Comment by rfrandse** [comment] 2020-03-28 10:50
refresh

**Comment by rfrandse** [comment] 2020-03-29 10:48
refresh

**Comment by rfrandse** [comment] 2020-03-30 10:49
refresh

**Comment by rfrandse** [comment] 2020-03-31 10:50
refresh

**Comment by rfrandse** [comment] 2020-04-01 10:50
refresh

**Comment by rfrandse** [comment] 2020-04-02 10:48
refresh

**Comment by rfrandse** [comment] 2020-04-03 10:50
refresh

**Comment by rfrandse** [comment] 2020-04-03 14:56
refresh

**Comment by rfrandse** [comment] 2020-04-04 10:49
refresh

**Comment by rfrandse** [comment] 2020-04-05 10:44
refresh

**Comment by rfrandse** [comment] 2020-04-06 10:48
refresh

**Comment by rfrandse** [comment] 2020-04-07 10:51
refresh

**Comment by rfrandse** [comment] 2020-04-08 10:51
refresh

**Comment by rfrandse** [comment] 2020-04-09 10:49
refresh

**Comment by rfrandse** [comment] 2020-04-10 10:50
refresh

**Comment by rfrandse** [comment] 2020-04-11 10:50
refresh

**Comment by rfrandse** [comment] 2020-04-17 10:48
refresh

**Comment by rfrandse** [comment] 2020-05-10 10:51
refresh

**Comment by rfrandse** [comment] 2020-05-12 10:54
refresh

**Comment by rfrandse** [comment] 2020-05-13 10:52
refresh

**Comment by rfrandse** [comment] 2020-06-06 10:55
refresh

**Comment by rfrandse** [comment] 2020-06-07 10:49
refresh

**Comment by rfrandse** [comment] 2020-06-08 10:53
refresh

**Comment by rfrandse** [comment] 2020-06-09 10:54
refresh

**Comment by rfrandse** [comment] 2020-06-10 10:55
refresh

**Comment by rfrandse** [comment] 2020-06-11 10:54
refresh

**Comment by rfrandse** [comment] 2020-06-12 10:54
refresh

**Comment by rfrandse** [comment] 2020-06-13 10:50
refresh

**Comment by rfrandse** [comment] 2020-06-14 10:45
refresh

**Comment by rfrandse** [comment] 2020-06-15 10:47
refresh

**Comment by mzipse** [comment] 2020-06-15 18:00
Removing @wangkair as the owner as I don't believe she will be finishing this work.  Let me know if anyone disagrees.  Carol, if you are able, can you document what is completed and what is left to be done here?

**Comment by rfrandse** [comment] 2020-06-16 10:47
refresh

**Comment by rfrandse** [comment] 2020-06-17 10:48
refresh

**Comment by rfrandse** [comment] 2020-06-18 10:46
refresh

**Comment by rfrandse** [comment] 2020-06-19 10:46
refresh

**Comment by rfrandse** [comment] 2020-06-20 10:45
refresh

**Comment by rfrandse** [comment] 2020-06-21 10:45
refresh

**Comment by rfrandse** [comment] 2020-06-22 10:45
refresh

**Comment by rfrandse** [comment] 2020-06-23 10:46
refresh

**Comment by rfrandse** [comment] 2020-06-25 10:48
refresh

**Comment by rfrandse** [comment] 2020-06-26 10:48
refresh

**Comment by rfrandse** [comment] 2020-06-27 10:45
refresh

**Comment by rfrandse** [comment] 2020-06-28 10:46
refresh

**Comment by rfrandse** [comment] 2020-07-02 10:49
refresh

**Comment by rfrandse** [comment] 2020-07-03 10:47
refresh

**Comment by rfrandse** [comment] 2020-07-04 10:46
refresh

**Comment by rfrandse** [comment] 2020-07-05 10:49
refresh

**Comment by rfrandse** [comment] 2020-07-06 10:55
refresh

**Comment by rfrandse** [comment] 2020-07-07 10:46
refresh

**Comment by rfrandse** [comment] 2020-07-08 10:51
refresh

**Comment by rfrandse** [comment] 2020-07-10 10:52
refresh

**Comment by rfrandse** [comment] 2020-07-11 10:47
refresh

**Comment by rfrandse** [comment] 2020-07-12 10:44
refresh

**Comment by rfrandse** [comment] 2020-07-13 10:45
refresh

**Comment by rfrandse** [comment] 2020-07-14 10:46
refresh

**Comment by rfrandse** [comment] 2020-07-15 10:47
refresh

**Comment by rfrandse** [comment] 2020-07-16 10:47
refresh

**Comment by rfrandse** [comment] 2020-07-17 10:46
refresh

**Comment by rfrandse** [comment] 2020-07-18 10:47
refresh

**Comment by rfrandse** [comment] 2020-07-19 10:45
refresh

**Comment by rfrandse** [comment] 2020-07-20 10:46
refresh

**Comment by rfrandse** [comment] 2020-07-21 10:47
refresh

**Comment by rfrandse** [comment] 2020-07-22 10:53
refresh

**Comment by rfrandse** [comment] 2020-07-23 10:47
refresh

**Comment by rfrandse** [comment] 2020-07-24 10:48
refresh

**Comment by rfrandse** [comment] 2020-07-25 10:45
refresh

**Comment by rfrandse** [comment] 2020-07-26 10:46
refresh

**Comment by rfrandse** [comment] 2020-07-27 10:47
refresh

**Comment by rfrandse** [comment] 2020-07-28 10:47
refresh

**Comment by rfrandse** [comment] 2020-07-29 10:49
refresh

**Comment by rfrandse** [comment] 2020-07-30 10:48
refresh

**Comment by rfrandse** [comment] 2020-07-31 10:47
refresh

**Comment by rfrandse** [comment] 2020-08-01 10:46
refresh

**Comment by rfrandse** [comment] 2020-08-02 10:47
refresh

**Comment by rfrandse** [comment] 2020-08-03 10:53
refresh

**Comment by rfrandse** [comment] 2020-08-04 10:55
refresh

**Comment by rfrandse** [comment] 2020-08-05 10:49
refresh

**Comment by rfrandse** [comment] 2020-08-06 10:55
refresh

**Comment by rfrandse** [comment] 2020-08-07 10:56
refresh

**Comment by rfrandse** [comment] 2020-08-08 10:48
refresh

**Comment by rfrandse** [comment] 2020-08-09 10:46
refresh

**Comment by rfrandse** [comment] 2020-08-10 10:49
refresh

**Comment by rfrandse** [comment] 2020-08-11 10:54
refresh

**Comment by rfrandse** [comment] 2020-08-12 10:57
refresh

**Comment by rfrandse** [comment] 2020-08-13 10:54
refresh

**Comment by rfrandse** [comment] 2020-08-14 10:57
refresh

**Comment by rfrandse** [comment] 2020-08-15 10:48
refresh

**Comment by rfrandse** [comment] 2020-08-16 10:48
refresh

**Comment by rfrandse** [comment] 2020-08-17 10:52
refresh

**Comment by rfrandse** [comment] 2020-08-18 10:58
refresh

**Comment by rfrandse** [comment] 2020-08-20 10:55
refresh

**Comment by rfrandse** [comment] 2020-08-24 10:49
refresh

**Comment by rfrandse** [comment] 2020-08-25 10:48
refresh

**Comment by rfrandse** [comment] 2020-08-26 10:49
refresh

**Comment by rfrandse** [comment] 2020-08-27 10:50
refresh

**Comment by rfrandse** [comment] 2020-08-28 10:49
refresh

**Comment by rfrandse** [comment] 2020-08-29 10:47
refresh

**Comment by rfrandse** [comment] 2020-08-30 10:48
refresh

**Comment by rfrandse** [comment] 2020-08-31 10:32
refresh

**Comment by rfrandse** [comment] 2020-09-01 10:50
refresh

**Comment by rfrandse** [comment] 2020-09-02 10:51
refresh

**Comment by rfrandse** [comment] 2020-09-04 10:49
refresh

**Comment by rfrandse** [comment] 2020-09-05 10:48
refresh

**Comment by rfrandse** [comment] 2020-09-06 10:48
refresh

**Comment by rfrandse** [comment] 2020-09-08 10:50
refresh

**Comment by rfrandse** [comment] 2020-09-09 10:52
refresh

**Comment by rfrandse** [comment] 2020-09-10 10:52
refresh

**Comment by rfrandse** [comment] 2020-09-11 10:50
refresh

**Comment by rfrandse** [comment] 2020-09-12 10:56
refresh

**Comment by rfrandse** [comment] 2020-09-13 10:48
refresh

**Comment by rfrandse** [comment] 2020-09-14 10:50
refresh

**Comment by rfrandse** [comment] 2020-09-15 10:50
refresh

**Comment by rfrandse** [comment] 2020-10-30 11:02
refresh

**Comment by rfrandse** [comment] 2020-10-31 10:55
refresh

**Comment by rfrandse** [comment] 2020-11-19 11:53
refresh

**Comment by lxwinspur** [comment] 2021-01-04 02:24
Hi, @mzipse 
Could we close this epic?

**Comment by rfrandse** [comment] 2021-01-29 11:53
refresh

**Comment by rfrandse** [comment] 2021-02-11 11:44
refresh

**Comment by mzipse** [comment] 2021-02-12 23:06
We cannot close this yet.  We confirmed that there is more work to do from a PLDM perspective.  This function can be initiated from the Host OS.  So the Host will need to communicate via PLDM to the BMC to set this timed power on function.  This design topic has been identified but not clear how soon we will get to this.  We will create a new PLDM story and link to this Epic once we understand the details of the PLDM design.

**Comment by rfrandse** [comment] 2021-04-12 10:55
refresh

**Comment by rfrandse** [comment] 2021-04-13 10:55
refresh

**Comment by mzipse** [comment] 2021-04-25 17:46
Timed Power on work is now closed.  Confirmed this with the PLDM team and Andrew.

**Closed by mzipse** 2021-04-25 17:46 UTC
Labels: Epic, ReadyForDev, Test on WSP-TAC, prio_medium
