### ISSUE TITLE
Host Error handling

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#217] opened 2018-11-14 09:41 UTC
Need to provide support for PEL type error log natively from BMC.
    - Currently BMC puts esel blob as part of the BMC error log and one callout supported.
    - Looking for detailed  error handling from BMC side , like Bus/fru callout and other related info.x
    - BMC is responsible for adding FRU callout and location code in the HB error log.
    - BMC is responsible for handling BUS specific error handling , FRU,cable callouts.
    - PE required consistency in the error log to use there custom tools.

**Comment by rfrandse** [comment] 2019-01-15 22:12
refresh

**Comment by rfrandse** [comment] 2019-01-15 22:24
refresh

**Comment by rfrandse** [comment] 2019-02-18 02:11
refresh

**Comment by rfrandse** [comment] 2019-02-25 02:11
refresh

**Comment by rfrandse** [comment] 2019-03-03 14:12
refresh

**Comment by rfrandse** [comment] 2019-03-10 13:12
refresh

**Comment by rfrandse** [comment] 2019-03-17 13:12
refresh

**Comment by rfrandse** [comment] 2019-03-24 13:12
refresh

**Comment by rfrandse** [comment] 2019-03-31 13:13
refresh

**Comment by rfrandse** [comment] 2019-04-07 13:13
refresh

**Comment by rfrandse** [comment] 2019-04-14 13:13
refresh

**Comment by rfrandse** [comment] 2019-04-21 13:14
refresh

**Comment by rfrandse** [comment] 2019-04-28 13:15
refresh

**Comment by mzipse** [comment] 2019-05-03 20:47
@spinler I wonder if this Epic is a duplicate of some of the Epics that you created?

**Comment by spinler** [comment] 2019-05-03 21:17
Yea, I would say https://github.com/ibm-openbmc/dev/issues/400 and https://github.com/ibm-openbmc/dev/issues/401 and maybe others

**Comment by rfrandse** [comment] 2019-05-12 13:20
refresh

**Comment by rfrandse** [comment] 2019-05-19 13:19
refresh

**Comment by rfrandse** [comment] 2019-05-26 13:26
refresh

**Comment by mzipse** [comment] 2019-05-29 21:20
@ojayanth , I'd like to close this and reference #755, #756 and #401 .  Assuming you agree, please close.

**Comment by rfrandse** [comment] 2019-06-02 13:32
refresh

**Comment by rfrandse** [comment] 2019-06-09 13:32
refresh

**Comment by rfrandse** [comment] 2019-06-23 13:36
refresh

**Comment by spinler** [comment] 2019-07-12 19:03
Closing this one.  covered elsewhere.

**Closed by spinler** 2019-07-12 19:03 UTC
Labels: prio_high_2, spnext
