### ISSUE TITLE
GUI : Design : Responsive Site Header

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1759] opened 2020-02-24 21:14 UTC
## Use Case
As a user viewing the application on a small screen or resized viewport, I want to be able to view and reference useful information, so that I can easily determine the state of my server and complete tasks more quickly.

### Branding Considerations
Community members have expressed concern with the height of the header. The small height of the header will not accommodate company logos above 100px in height (roughly). We need to consider this and determine how to support logos of varying sizes (including width). There are various possibilities, but we will also want to design with the expand/collapse navigation in mind.

## As Is
![image](https://user-images.githubusercontent.com/1183515/75191732-89be4080-5718-11ea-8da8-b437bf09c23b.png)

## Related Stories
#1292 - Revisit Header 
#1655 - Accommodate multiple logo sizes (Closed as duplicate)

## References/Resources
- feature discovery: https://ibm.ent.box.com/notes/638827914802

**Comment by derick-montague** [comment] 2020-02-28 13:53
1. Please use this Invision screen as you work through this change. 
1. The profile icon will have an associated dropdown and should include the user name following the icon.

![image](https://user-images.githubusercontent.com/1183515/75554093-45c08980-59ff-11ea-8a50-51005ab0549c.png)

https://ibm.invisionapp.com/d/main#/console/15354657/319398053/preview

**Comment by dixsie** [comment] 2020-03-02 14:38
Minimum width 320px

**Comment by ParishrutB** [comment] 2020-03-03 10:32
This is the Mural where we are posting screenshots and our initial observations. https://app.mural.co/t/ibmpower1831/m/ibmpower1831/1582793816628/db75cbe89d805f79e3f646ef819794d4c4e46cf8

**Comment by yoshiemuranaka** [comment] 2020-05-18 16:40
@derick-montague is this a duplicate of #2094 ?

**Comment by derick-montague** [comment] 2020-05-19 04:24
> @derick-montague is this a duplicate of #2094 ?

No. This is for future discovery work to see if we want to change what is displayed in the header based on some early user feedback. I broke this out and using the other story for the layout of the existing header content.

**Comment by nicoleconser** [comment] 2020-07-15 17:25
Added a comment re: **Logical memory block size** pending IPL task FYI @priyanka-pillai97 @derick-montague

**Comment by nicoleconser** [comment] 2020-07-28 23:20
A customer recently pointed out to us that the **system name** is missing from our header. Apparently “system name” is useful information to display at all times, since it needs to be referenced while on multiple different pages. 

I’m trying to find out if **hostname** is the same thing as **system name**, since we decided during a recent GUI workgroup meeting to remove host name from the header.

**Comment by derick-montague** [comment] 2020-07-28 23:43
> Apparently “system name” is useful information to display at all times, since it needs to be referenced while on multiple different pages.

This will also be conversation with the community since we moved away from this and the discussion of having it on the overview and network settings page was the decision made in the design community workgroup.

**Comment by derick-montague** [comment] 2020-07-29 19:41
> A customer recently pointed out to us that the **system name** is missing from our header. Apparently “system name” is useful information to display at all times, since it needs to be referenced while on multiple different pages.
> 
> I’m trying to find out if **hostname** is the same thing as **system name**, since we decided during a recent GUI workgroup meeting to remove host name from the header.

https://github.com/ibm-openbmc/dev/issues/2211#issuecomment-665862854

**Comment by nicoleconser** [comment] 2020-07-29 19:43
Another consideration is to add **System name** to the header (not necessarily editable from the header, but viewable for quick reference from any page the user is on). 

Recently, a customer (very randomly - we did not ask, and we were not focusing on the header) pointed out that _System name_ is missing from the header in our Vue prototypes. She stated that _System name_ is useful to see at all times, because it gives you a sense of "where I am" (i.e. I have 1000s of servers in my data center - and 12 GUI tabs open in my browser - which server am I on?). 

@ParishrutB is currently considering making **System name** editable from the Overview screen, as it was in the Angular app. 

Full Slack conversation is [here](https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1595976814152100). 

**side note to prevent confusion:** It was determined during a GUI workgroup meeting that **Hostname** is not important enough information to live in the Header, but _Hostname_ is different from _System name_.

**Closed** 2020-07-29 20:05 UTC
Labels: GUI, Milestone Tgt, UI Design
