### ISSUE TITLE
GUI : FED : Hardware status - Chassis table missing properties

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2311] opened 2020-06-18 20:32 UTC
## Overview
The Chassis table on the Hardware status page is missing properties that were defined in the original design. When these properties are available on the backend, update the table to show missing properties:

- [x] CCIN (Model in Redfish)
- [ ] Hardware type (Name in Redfish)
- [x] Serial number (SerialNumber in Redfish)
- [ ] Identify LED (LocationIndicatorActive in Redfish) - mapped to Identity LED for System - as per Vishwa.
- [x] Part number(PartNumber in Redfish)
- [ ] Manufacturer (Manufacturer in Redfish)
- [x] Health(Health in Redfish)
- [x] State(State in Redfish)
- [x] Chassis type(ChassisType in Redfish)
- [ ] Asset tag(AssetTag in Redfish)
- [ ] Indicator LED(IndicatorLED in Redfish)
- [ ] Location(Location in Redfish)
- [ ] Max power watts(MaxPowerWatts in Redfish)
- [ ] Min power watts(MinPowerWatts in Redfish)
- [ ] Power(PowerState in Redfish)

## Notes
- [ ] Design/layout has changed from what is currently in InVision mockup

## Final Invision Mockup
- [ ] https://ibm.invisionapp.com/share/VQO16ZXAGKE#/screens/319963050

**Comment by ParishrutB** [comment] 2021-04-06 11:19
As per Santosh, Redfish queries for both Chassis and Motherboard, which are duplicate of each other. There were chats with @gtmills to remove one of these in the backend.

**Comment by Srisuk** [comment] 2021-05-03 14:51
Many keys are missing, keys will be available in the fw-20.
Slack conversation: https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1620051083069600?thread_ts=1619086127.353600&cid=C0Q6TQP5Z

**Comment by sandeepasingh116** [comment] 2021-05-06 16:47
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/42963

**Comment by Srisuk** [comment] 2021-05-20 06:56
The schema used to get the missing keys: https://redfish.dmtf.org/schemas/v1/Chassis.v1_15_0.json

**Comment by derick-montague** [comment] 2021-05-28 12:15
Blocker: Waiting for LocationIndicators to be present in the API before merge is possible.

**Comment by derick-montague** [comment] 2021-05-28 17:03
@sandeepasingh116 - It looks like all the FEDs are assigned as reviewers. Can you work with the team to determine who should be assigned and who should be CC'd?

**Closed** 2021-07-01 16:52 UTC
Labels: Blocked, GUI, Milestone Tgt, UI FED
