### ISSUE TITLE
GUI : FED : Hardware status - System table missing properties

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2308] opened 2020-06-18 20:24 UTC
## Overview
The system table on the Hardware status page is missing properties that were defined in the original design. When these properties are available on the backend, update the table to show missing properties:
- [x] Model (Model in Redfish)
- [x] Name (Name in Redfish)
- [x] Serial Number (SerialNumber in Redfish)
- [x] Memory Summary (Memory summary in Redfish)
- [x] Processor Summary (Processor summary in Redfish)
- [ ] Part number(PartNumber in Redfish)
- [ ] Location number (LocationNumber in Redfish)
- [x] Identify LED (LocationIndicatorActive in Redfish)
- [ ] Manufacturer (Manufacturer in Redfish)
- [x] Sub Model(SubModel in Redfish)
- [ ] Asset Tag(AssetTag in Redfish)

## Notes
- [ ] Design/layout has changed from what is currently in InVision mockup

## Final Invision Mockup
- [ ] https://ibm.invisionapp.com/d/main#/console/15347903/319961436/preview

**Comment by derick-montague** [comment] 2020-08-11 13:44
@gtmills wondering when these might be ready on the backend. 

Slack chat: https://ibm-systems-power.slack.com/archives/GQR6QQXT8/p1597078702004300

**Comment by gtmills** [comment] 2020-08-11 14:13
Maybe since we have model here already we done with CCIN ?
Model property in redfish.dmtf.org/schemas/v1/Assembly.v1_2_3.json map to a CCIN

**Comment by ParishrutB** [comment] 2021-04-06 11:25
As per the meeting with Santosh on 3/30, backend code for this has been merged.

**Comment by Srisuk** [comment] 2021-04-09 07:34
As per meeting with @santoshpuranik "Manufacturer" need to be get confirmed from @santoshpuranik.

**Comment by Srisuk** [comment] 2021-04-09 10:17
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/42074

**Closed** 2021-07-13 13:42 UTC
Labels: GUI, Milestone Tgt, UI FED

**Comment by derick-montague** [comment] 2021-08-16 12:23
System VPD does not contain a location code: https://ibm-systems-power.slack.com/archives/C019G4UGZDY/p1629108892019100
